// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU_B0GxG_CYspQKdOHSOJq_HeWYHORBVQ',
    appId: '1:481238350742:web:9cf98e529fa54943453bb7',
    messagingSenderId: '481238350742',
    projectId: 'likort-creatives-app',
    authDomain: 'likort-creatives-app.firebaseapp.com',
    storageBucket: 'likort-creatives-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjr2cPgjv2U0jcZ0Jf-3T8bJckOqDx0-E',
    appId: '1:481238350742:android:ff234917abc9c892453bb7',
    messagingSenderId: '481238350742',
    projectId: 'likort-creatives-app',
    storageBucket: 'likort-creatives-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_g59hXvtNvZXGzjUMsZlw7uV6nq-4934',
    appId: '1:481238350742:ios:c01c93484417d7df453bb7',
    messagingSenderId: '481238350742',
    projectId: 'likort-creatives-app',
    storageBucket: 'likort-creatives-app.firebasestorage.app',
    iosBundleId: 'com.example.likort',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_g59hXvtNvZXGzjUMsZlw7uV6nq-4934',
    appId: '1:481238350742:ios:c01c93484417d7df453bb7',
    messagingSenderId: '481238350742',
    projectId: 'likort-creatives-app',
    storageBucket: 'likort-creatives-app.firebasestorage.app',
    iosBundleId: 'com.example.likort',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAU_B0GxG_CYspQKdOHSOJq_HeWYHORBVQ',
    appId: '1:481238350742:web:af2a0eac97754263453bb7',
    messagingSenderId: '481238350742',
    projectId: 'likort-creatives-app',
    authDomain: 'likort-creatives-app.firebaseapp.com',
    storageBucket: 'likort-creatives-app.firebasestorage.app',
  );

}