// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2qhMdgzh9_wr963DopW91XcIYdrtgf6s',
    appId: '1:813285727134:web:26ca30d84dad5a1b12148f',
    messagingSenderId: '813285727134',
    projectId: 'shop-app-43b6d',
    authDomain: 'shop-app-43b6d.firebaseapp.com',
    databaseURL: 'https://shop-app-43b6d-default-rtdb.firebaseio.com',
    storageBucket: 'shop-app-43b6d.appspot.com',
    measurementId: 'G-KBRK6P0WRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGjbRgvgWPvxkX1M19MbKyEBJldZ-CqIM',
    appId: '1:813285727134:android:9627b6b9beeeedb212148f',
    messagingSenderId: '813285727134',
    projectId: 'shop-app-43b6d',
    databaseURL: 'https://shop-app-43b6d-default-rtdb.firebaseio.com',
    storageBucket: 'shop-app-43b6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw3Kcr7kJuNtNgXP7FgYM02L4EgD3IMVk',
    appId: '1:813285727134:ios:030ff577450280a012148f',
    messagingSenderId: '813285727134',
    projectId: 'shop-app-43b6d',
    databaseURL: 'https://shop-app-43b6d-default-rtdb.firebaseio.com',
    storageBucket: 'shop-app-43b6d.appspot.com',
    iosBundleId: 'com.example.likort',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw3Kcr7kJuNtNgXP7FgYM02L4EgD3IMVk',
    appId: '1:813285727134:ios:030ff577450280a012148f',
    messagingSenderId: '813285727134',
    projectId: 'shop-app-43b6d',
    databaseURL: 'https://shop-app-43b6d-default-rtdb.firebaseio.com',
    storageBucket: 'shop-app-43b6d.appspot.com',
    iosBundleId: 'com.example.likort',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2qhMdgzh9_wr963DopW91XcIYdrtgf6s',
    appId: '1:813285727134:web:f64bb5783d941daf12148f',
    messagingSenderId: '813285727134',
    projectId: 'shop-app-43b6d',
    authDomain: 'shop-app-43b6d.firebaseapp.com',
    databaseURL: 'https://shop-app-43b6d-default-rtdb.firebaseio.com',
    storageBucket: 'shop-app-43b6d.appspot.com',
    measurementId: 'G-TCVDR2D91W',
  );

}